apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::064177271201:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ITECZMVKP8QX
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::064177271201:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-11T18:48:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "915"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2a5c3a61-fe77-4cb7-b17f-0e055ae678e3
